---
title: "tidy_tuesday_week_14"
author: "Jobel Y. Villafane Pagan"
date: "2024-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,  fig.path = "../Output/")
```
# Introduction
Introduction Tidy Tuesday is an international community of R enthusiasts that create visuals from the same dataset. The goal is to practice plotting and learn something new every week.This week is about traffic.


# Libraries
```{r}
library(tidytuesdayR)
library(janitor)
library(tidyverse)
library(ggplot2)
library(tidytext)
```
# data
```{r}
tuesdata <- tidytuesdayR::tt_load(2024, week = 49)

A64_traffic <- tuesdata$A64_traffic

# Clean column names
A64_traffic <- A64_traffic %>% clean_names()
```

# Plot

```{r}
# Convert the 'time_period_ending' to a proper time format
A64_traffic <- A64_traffic %>%
  mutate(time_period_ending = hms::as_hms(time_period_ending))

# Plot total volume by time of day, colored by sensor status
ggplot(A64_traffic, aes(x = time_period_ending, y = total_volume, color = status)) +
  geom_line(alpha = 0.8, size = 1) +
  labs(
    title = "Traffic Volume Throughout the Day",
    x = "Time of Day",
    y = "Total Volume",
    color = "Sensor Status"
  ) +
  scale_x_time(
    breaks = scales::breaks_width("2 hours"),
    labels = scales::label_time(format = "%H:%M")
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.text.x = element_text(angle = 45, hjust = 1), ,
    legend.position = "none" 
      
  )
```

